name: Ruby SimpleCov
description: Github action to print a comment on the pull request with coverage changes from simplecov
author: D1ceWard
inputs:
  token:
    description: Github generated token
    required: true
  threshold:
    description: Threshold
    default: "100"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
