name: Ruby SimpleCov
description: Ruby SimpleCov github action reporting
author: D1ceWard
inputs:
  token:
    description: Github generated token
    required: true
  threshold:
    description: Threshold
    default: "100"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
